PIECE_NAMES = ("Pawn", "Knight", "Bishop", "Rook", "Queen", "King")
PIECE_ABB = ("P", "N", "B", "R", "Q", "K")
LETTERS = ("a", "b", "c", "d", "e", "f", "g", "h")
UPP_LETTERS = ("A", "B", "C", "D", "E", "F", "G", "H")
COLORS = ("White", "Black")